name: NeincraftPlugin
version: @version@
main: de.neincraft.neincraftplugin.NeincraftPlugin
api-version: 1.18
authors: [ Mark_225 ]
softdepend:
  - BlueMap

commands:
  plot:
    aliases:
      - gs
    permission: neincraft.commands.user.plot
  plotadmin:
    aliases:
      - gsadmin
    permission: neincraft.commands.admin.plotadmin
  stats:
    permission: neincraft.commands.user.stats
  testlang:
    permission: neincraft.commands.admin.testlang
  home:
    permission: neincraft.commands.user.home
    aliases:
      - spawn
  portal:
    permission: neincraft.commands.admin.portal
  timber:
    permission: neincraft.commands.user.timber
  label:
    permission: neincraft.commands.admin.label
  storage:
    permission: neincraft.commands.user.storage
    aliases:
      - s
  tpa:
    permission: neincraft.commands.user.tpa
    aliases:
      - tpaccept
      - tpahere
  echo:
    permission: neincraft.commands.user.echo
  discord:
    permission: neincraft.commands.user.discord
  evacuate:
    permission: neincraft.commands.admin.evac
    aliases:
      - evac