name: NeincraftPlugin
version: @version@
main: de.neincraft.neincraftplugin.NeincraftPlugin
api-version: 1.17
authors: [ Mark_225 ]

commands:
  plot:
    aliases:
      - gs
    permission: neincraft.commands.user.plot
  plotadmin:
    aliases:
      - gsadmin
    permission: neincraft.commands.admin.plotadmin
  stats:
    permission: neincraft.commands.user.stats
  testlang:
    permission: neincraft.commands.admin.testlang
  home:
    permission: neincraft.commands.user.home
    aliases:
      - spawn
  portal:
    permission: neincraft.commands.admin.portal
  timber:
    permission: neincraft.commands.user.timber